#!/bin/zsh
# vim: ts=8 sw=8
ME=${0:t:r}
USAGE="usage: ${ME} [-n num] [file...]"
n=16
while getopts :n: c
do
        case "$c" in
        n)      n=${OPTARG};;
	*)
		echo "${ME}: unknown switch (-${OPTARG})." >&2
		echo "${USAGE}" >&2
		exit 1
		;;
        esac
done
shift $(expr $OPTIND - 1)
# awk -f ${mydir}/${ME}.awk -v n=${n} ${*:--}
awk -f "${0:t:r}.awk" -v n=${n} "${@:--}"
