#!/bin/zsh
# vim: ts=8 sw=8
export	PATH="${0:h}:${PATH}"
ME="${0:t:r}"
USAGE="usage: ${ME} [-t] [file ...]"
TABS='unexpand -a'
NONFATAL=
while getopts :t c
do
	case "${c}" in
	t)	TABS='expand'
		;;
	*)	echo "${ME}: unknown switch (-${OPTARG})" >&2
		NONFATAL=yes
		;;
	esac
done
if [ "${NONFATAL}" ]; then
	echo "${USAGE}" >&2
	exit 1
fi
shift	$(( ${OPTIND} - 1 ))
cat "${@}" | tr -d '\r' | parens | ifnest -c | comment | castfmt | eval ${TABS}
