#!/bin/zsh
# vim: ts=8 sw=8
ME="${0:t:r}"
USAGE="usage: ${ME} [-c] [file...]"
doComment=0
while getopts :c c
do
	case "$c" in
	c)
		doComment=1
		;;
	*)
		echo "${ME}: unknown switch (-${OPTARG})" >&2
		echo "$USAGE" >&2
		exit 1
		;;
	esac
done
shift $(( ${OPTIND} - 1 ))
expand $*								|
	awk -f "${0:r}.awk" -v doComment="${doComment}"
